### ISSUE TITLE
Stairs in the Slambert don't work

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#1021]
We're going to have to use the edge the player is walking towards rather than the middle of the collision poly to check if they're close enough on the Y axis to move to it

**Comment by Chocolate06** [comment]
staircase leading to Dran

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/16a8e1e0-ccea-4fb4-92ca-eb281d3e16cb)

**Comment by Chocolate06** [comment]
Front staircase of castle

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/34f23a94-9cc9-4610-b61f-fded9d67bdf1)

**Comment by Chocolate06** [comment]
Staircase in castle, but only sometimes get stuck

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/2a163744-42c8-4d86-a0b7-b1e9418a2a5d)
