### ISSUE TITLE
Garbage outside submap during boat rocking animation

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#1053]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/02692d89-b336-4139-bba3-763d50cb7c50)

**Comment by LordMonoxide** [comment]
Parts of submaps can be untextured, this fix initialized the textures with 0s
