### ISSUE TITLE
Billowing smoke texture is all crazy.

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#119]
[Bug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9690784/Bug.zip)

I missed a screenshot but I'll find it again and take one.

**Comment by Kona-lod** [comment]
Was in Basil upon entering the town and upon going to Lavitz's Mom's Roof

**Comment by Kona-lod** [comment]
![image](https://user-images.githubusercontent.com/114179389/193420017-b499e314-2e66-4f7f-bfaf-015a8278dd83.png)


It was the same texture error when going onto Lavitz's roof

**Comment by LordMonoxide** [comment]
Smoke seems to change depending on what else is being rendered. Maybe it's missing a draw mode packet or something?
