### ISSUE TITLE
Dragoon Icon does not load during battle

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#124]
![image](https://user-images.githubusercontent.com/114179389/193850376-7792a823-6ee7-4eed-9356-2d063de90fc9.png)

Realizing now I don't have the most recent build. Will reload and attempt. If issue is fixed, I will delete this. If this post is still up, issue persists.

**Comment by LordMonoxide** [comment]
Already fixed in latest version
