### ISSUE TITLE
Potential bug in drop-rate method

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#125]
Some corroborating evidence of an error in drop rate as follows:

- More than expected "Spear" drops off Mermen in the Serdio Swamps
- More than expected items off first Virage fight (2 Healing Potion and one Mind Purifier)
- 5 Satchets off of Orcs in Home of Giganto in a half hour. Drop rate should be around 2%.

Future evidence to be detailed here.

**Comment by Kona-lod** [comment]
> Serdio Swamps

Read "Marshlands"

**Comment by Kona-lod** [comment]
Both Down Burst and Plate Mail from Feyrbrand/Greham.

**Comment by dragoonsouls** [comment]
I went in a grinding quest in Home of Gigantos... and in a near 10hs of grinding, only 8 sachets were dropped, while in a run i made some time ago (in emulator, so as retail) in 10 hs i got 12 sachets at least, so, maybe you were lucky or i was pretty unlucky... for other items yeah, i saw specially in disk 1 to be more frequent multiple drops. but in disk 2 was just "average".

**Comment by theflyingzamboni** [comment]
> > Serdio Swamps
> 
> Read "Marshlands"
Swamp is actually more accurate lol. Swamps are forested wetlands, while marshes are dominated by grasses. Nothing to do with the bug, but there it is.

**Comment by theflyingzamboni** [comment]
@LordMonoxide I think this issue can be closed. If it was bugged, it's not now. The decomp does `if(simpleRand() * 100 >> 16 < drop.chance())`, and I can confirm that ghidra gives the same calculation.
