### ISSUE TITLE
Dragoon spirits and lights render darker than expected

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#138]
![image](https://user-images.githubusercontent.com/114020799/195961916-5a74d38f-ea98-4e87-abb6-91eeaf7181f2.png)

**Comment by LordMonoxide** [comment]
I have a strong suspicion they are being rendered with (B+F)/2 blending instead of B+F

**Comment by LordMonoxide** [comment]
Resolved in graphics rewrite
