### ISSUE TITLE
Post battle magic unlocks are the wrong color

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#139]
github
![image](https://user-images.githubusercontent.com/114020799/195963530-781d48ca-6606-4472-9b60-ace512fe6a46.png)
Retail:
![image](https://user-images.githubusercontent.com/114020799/195963683-7ba93ef0-a64a-479c-aaf7-7757d9f38b3c.png)

**Comment by djcarvey** [comment]
screenshot taken from https://youtu.be/AMWmG_0wI_8?t=3417

**Comment by LordMonoxide** [comment]
Resolved
