### ISSUE TITLE
Moon light placed party member into state of pseudo death

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#140]
I have been unable to recreate this, but here's what my game looked like after I tried to heal lavitz with the Moon Light spell
![image](https://user-images.githubusercontent.com/114020799/195998783-2c5a595b-98e2-43ba-921a-fc924bd1c1a0.png)

It was then lavitz's turn, as shown in the screenshot. I was able to attack normally, but Lavitz re-entered his death pose once the attack finished. The elite warden then used gushing magma. Lavitz stood up to receive the damage (30-40 points), fell down again, and never got another turn, so I think that attack killed him.

Here's everything I remember about the situation for anyone trying to reproduce it. On the way to Hellena at the end of disk 1, I ran into an OOPARTS which killed Lavitz. When I entered Hellena and ran into the first patrolling guard, Lavitz was at 1 HP. I decided to use Shana to heal him up. I wanted to hear the full spell audio, so when I realized the animation was playing faster than the audio, I lowered the framerate to about 5 or 10 halfway through the spell (while the camera was panned towards the sky after following the arrow). Once I was sure the audio was over, I increased the framerate again. I do not believe I saw the usual heal number pop up at the end of the spell. When the light faded, Lavitz was on the floor.

**Comment by djcarvey** [comment]
I should probably clarify that I did not open the combat debugger at any point in this process (despite it likely being a good idea after seeing Lavtiz's state. oops)

**Comment by LordMonoxide** [comment]
So far we haven't been able to reproduce this. Any help would be appreciated.

**Comment by LordMonoxide** [comment]
We did see this happen again when Drew fought Lask Kraken, but may be fixed along with all of the other combat fixes. I'll leave this open until the end of this release cycle and if it hasn't popped back up, I'll close it.

**Comment by LordMonoxide** [comment]
Haven't been able to repro since, closing
