### ISSUE TITLE
Status effects are invisible

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#154]
At the very least, confusion does not render

**Comment by dragoonsouls** [comment]
pretty much continue happening... but now i think it's something to do with the usage of alpha channels for them... sometimes i get poisoned or confused and see some portions of the effect when looking through Battle Stage...

**Comment by LordMonoxide** [comment]
Fixed in 637c0ad
