### ISSUE TITLE
Disc Change screen coming up on loading

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#163]
Came up loading into Barrens. Was first loading screen on startup. Reproduced with the attached savestate.

**Comment by Kona-lod** [comment]
[Bug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9897160/Bug.zip)

**Comment by LordMonoxide** [comment]
This is normal behaviour, the disks switch on demand
