### ISSUE TITLE
Meru doesn't perform victory dance.

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#165]
Meru just stands in her battle stance. I feel empty without her adorable tumble.
[Bug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9901794/Bug.zip)
er adorable tumble.

Recreatable in attached save state by using Satchet on the Blue Bird. Will continue battle testing to see if it's common.

**Comment by Kona-lod** [comment]
I'm bad at seeing stuff. Rose doesn't do victory dance and it appears Dart is the only one who does? lol

**Comment by DrewUniverse** [comment]
To clarify on this, it's more that the character in slot one is the only one who will do a victory pose.

**Comment by LordMonoxide** [comment]
Duplicate of #73
