### ISSUE TITLE
Game Crash during Helena Prison [Steam Deck - Arch Linux]

### ISSUE THREAD

**Issue by majorjae** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#190]
Early on when you walk into where the prison cells start. And see the cutscene with the 2 guards moving the 2 prisoner soldiers. Right after one guards mention feeding the prisoners to the monster is when it crashes the game entirely.

**Comment by majorjae** [comment]
Sorry, just realized this is a duplicate.

**Comment by LordMonoxide** [comment]
Closing as duplicate, will log work in the other ticket

**Comment by LordMonoxide** [comment]
This has been resolved
