### ISSUE TITLE
in main.scripts Indels Castle Crash

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#210]
When you're talking with Albert reaching the Indels Castle first time a Crash is granted!... 
[Indels_Castle_Crash.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10361842/Indels_Castle_Crash.txt)

**Comment by LordMonoxide** [comment]
Resolved on that branch
