### ISSUE TITLE
Broken animated texture during Fletz dance

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#211]
![Bad submap texture animation](https://user-images.githubusercontent.com/437657/211120547-43f41e96-8305-4534-af38-30beb0cd0e3a.gif)

**Comment by theflyingzamboni** [comment]
Fixed by 3d81268e43990aa4d8651ad8294290c05142c916 and 39cce49a86f829aebc0a7620ce13fb7e7ccd0e6c
