### ISSUE TITLE
Zenebatos - Dart is not in Char List - Weapon Shop (main.scripts branch)

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#213]
There is no Crash or Softlock... but Dart is missing from the characters list when you try to buy equipment from Zenebatos Shop...
Maybe it's related to the No-Dart code?, or maybe it's part of the Script Engine Overhaul... 
![no_dart](https://user-images.githubusercontent.com/17453375/211178960-9f4f4d59-a347-4da3-8a18-b63c6b4cc072.png)
![no_dart_1](https://user-images.githubusercontent.com/17453375/211178962-c66127d3-96c0-47fe-9144-466b69da9a58.png)

**Comment by dragoonsouls** [comment]
Also i detect that Dart is missing from the Status Menu in the main menu
![no_dart_2](https://user-images.githubusercontent.com/17453375/211179513-31c5303e-b848-4562-b463-724c0e49919a.png)

**Comment by LordMonoxide** [comment]
I have a feeling this was due to the bug I fixed that was causing most chests to get reset. Can you confirm if this is fixed?

**Comment by LordMonoxide** [comment]
Resolved
