### ISSUE TITLE
Request Submap squishing (squish to 4:3 request)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#216]
In conversation with Corey, we discussed how submap (bg image) squishing is applied in retail and emulation. I am submitting this issue on the basis of creating parity with retail by restoring the squishing effect. For example, in retail and emulation, the Death Frontier's first submap is properly squished so that the Moon appears circular. In the decomp, this squishing effect is not applied. 

Corey mentioned that emulators can do global squishing, but cannot squish independent elements. In SC we are also currently limited to global squishing for sake of time involved, which would squish the 3D models in the process. 

I am hoping that the submap models were pre-widened by Sony as a measure of foresight. Either way, the main objective with this request is to get SC closer to parity with retail in terms of visual output. If the submap 3D models get squished and they are narrower than Sony intended, we can always look at a more involved solution down the road.

**Comment by DrewUniverse** [comment]
We have since learned that the BGs are intended to be squished, as evidenced by things like the aspect ratio of the Moon That Never Sets.

**Comment by LordMonoxide** [comment]
Resolved in 949f182d
