### ISSUE TITLE
Path between Evergreen Forest and Mountain of Mortal Dragon is broken

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#226]
If you walk to the mountain, you teleport back to the forest

**Comment by dragoonsouls** [comment]
While i was in Zenebatos i used Coolon to get into that place and check the bug, when i get in his destination selector, automatically send me to Forest (near Seles) to the last SubMap, and each time i called Coolon that happens... is returning to that point.
Here a full trace log
[World_M.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10527591/World_M.txt)

**Comment by LordMonoxide** [comment]
Resolved in 9046d466a9ec74c5114707bdba130781564c280e
