### ISSUE TITLE
Incorrect palettes being applied

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#23]
A lot of models have incorrect palettes applied to certain texture pieces (e.g. Dart's red boots, static-noise horses).

**Comment by theflyingzamboni** [comment]
This is also happening with the battle MCQ in Seles, and I assume any others, as well.

**Comment by LordMonoxide** [comment]
This is most noticeable on the horses and Fruegel, they'll be good references for fixing this

**Comment by LordMonoxide** [comment]
Fixed
