### ISSUE TITLE
Fletz cannot be entered again

### ISSUE THREAD

**Issue by Spyrokid77666** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#231]
Going to the entrance point does not open the enter screen.

**Comment by LordMonoxide** [comment]
I think this likely has to do with using modded ISOs

**Comment by Spyrokid77666** [comment]
Update: Severed Chains re-installed with the modded iso, issue fixed, cause of issue unknown

**Comment by LordMonoxide** [comment]
May have been an older file unpack version causing it. It's a good idea to re-unpack files whenever updating. Closing issue as resolved
