### ISSUE TITLE
Wisps on Phantom Ship don't show up

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#245]
![image](https://user-images.githubusercontent.com/1794288/218363241-034fd7b8-1911-411d-96b4-aef8e856cb41.png)

**Comment by dragoonsouls** [comment]
In main.tmd... still happening, maybe something about the submap positioning, displaced by 1 px so the Wisps objects and animations are not updated

**Comment by theflyingzamboni** [comment]
Fixed by 3d81268e43990aa4d8651ad8294290c05142c916 and 39cce49a86f829aebc0a7620ce13fb7e7ccd0e6c
