### ISSUE TITLE
Miranda attack camera on wrong character

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#246]
Full steps:
https://streamable.com/aho3q8

Bug @ 00:40

.dsav
https://www.mediafire.com/file/4is0lbof365a0lj/91.dsav/file

**Comment by LordMonoxide** [comment]
Note: same for Shana

**Comment by dragoonsouls** [comment]
could be something related to the values used by camera send by the script engine? or maybe some of the camera functions is broken?... since the branch main.tmd the camera issue is not solved but the improvement done is noticeable.

**Comment by LordMonoxide** [comment]
This was fixed by #454
