### ISSUE TITLE
Misaligned def, Sound thread crashed @ specific moon map

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#247]
Log:
![image](https://user-images.githubusercontent.com/29797557/218605291-4634f70c-372d-44d5-ab42-268eeb86174f.png)

Steps:
https://streamable.com/wjqlo0
Bug @ 00:16

.dsav:
https://www.mediafire.com/file/kirblx1bt5uenff/105.dsav/file

Explanation:
Loading on the moon, navigating to 2 screens before the end boss fight. As soon as you enter, the audio gets wonky, FPS gets low and the logger logs the above. No immediate crash.

**Comment by dragoonsouls** [comment]
thank's for the test @Ink230 at the moment SC chains support "retail play" uintil Zenebatos (when you finish there and change to Mayfil), so it's a good one to pay attention in the future...

**Comment by LordMonoxide** [comment]
Temporary patch in place to prevent this, will be fixed with audio rewrite
