### ISSUE TITLE
Divine Dragoon can not gain SP

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#273]
Divine Dragoon always has 0 SP gain. 

Divine Dragoon does gain SP however if you have Red-Eyed as well which is not possible normally.

**Comment by LordMonoxide** [comment]
This is due to Dart's d'lvl getting set to 0. Investigating further...

**Comment by LordMonoxide** [comment]
Closed in bd05502772b24f677c9394beb07ac459f0f4c7c8
