### ISSUE TITLE
Visual Issue - Lapto at Zenebatos (Law Launcher zone)

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#286]
The lapto in that zone get wrong UV data...
![Matrix_Lapto](https://user-images.githubusercontent.com/17453375/221459397-4ca78a30-cf90-41cd-8eac-66a86c313bb1.png)

**Comment by theflyingzamboni** [comment]
Fixed by 39cce49a86f829aebc0a7620ce13fb7e7ccd0e6c and 3d81268e43990aa4d8651ad8294290c05142c916
