### ISSUE TITLE
Item and equip lists show cursor simultaneously

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#294]
Both columns in the item/equipment list have the cursor showing regardless of which column the player is navigating, making it impossible to tell which list is being navigated. The cursor should only appear in whichever column is being actively navigated.

![image](https://user-images.githubusercontent.com/55669985/221749639-000ad375-81c9-4ae3-9df4-a8bd2a494072.png)

**Comment by Ink230** [comment]
This is also present in the PR #268
