### ISSUE TITLE
Crash when Dart takes out Dragon Block Staff at Divine Dragon Battle if he is not in middle

### ISSUE THREAD

**Issue by Spyrokid77666** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#309]
16:41:55.668 [GPU legend.game.scripting.ScriptManager:129] ERROR: Script 14 crashed!
16:41:55.668 [GPU legend.game.scripting.ScriptManager:130] ERROR: File 5054/1[2072]
16:41:55.668 [GPU legend.game.scripting.ScriptManager:131] ERROR: Parameters:
16:41:55.668 [GPU legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x23e
16:41:55.669 [GPU legend.game.scripting.ScriptManager:134] ERROR:   1: script[14].storage[18] 15
16:41:55.669 [GPU legend.game.scripting.ScriptManager:134] ERROR:   2: script[0x558] 0x11b06
16:41:55.669 [GPU legend.game.scripting.ScriptManager:137] ERROR: Storage:
16:41:55.669 [GPU legend.game.scripting.ScriptManager:139] ERROR:   1: 0xe
16:41:55.670 [GPU legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
16:41:55.670 [GPU legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
16:41:55.670 [GPU legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
16:41:55.671 [GPU legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
16:41:55.672 [GPU legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
16:41:55.672 [GPU legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
16:41:55.672 [GPU legend.game.scripting.ScriptManager:139] ERROR:   8: 0x90000
16:41:55.672 [GPU legend.game.scripting.ScriptManager:139] ERROR:   9: 0xffffffff
16:41:55.672 [GPU legend.game.scripting.ScriptManager:139] ERROR:   10: 0x0
16:41:55.673 [GPU legend.game.scripting.ScriptManager:139] ERROR:   11: 0xffffffff
16:41:55.673 [GPU legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
16:41:55.673 [GPU legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
16:41:55.673 [GPU legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
16:41:55.673 [GPU legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
16:41:55.674 [GPU legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
16:41:55.674 [GPU legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
16:41:55.674 [GPU legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
16:41:55.674 [GPU legend.game.scripting.ScriptManager:139] ERROR:   19: 0xf
16:41:55.674 [GPU legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
16:41:55.675 [GPU legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
16:41:55.675 [GPU legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
16:41:55.675 [GPU legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
16:41:55.675 [GPU legend.game.scripting.ScriptManager:139] ERROR:   24: 0xffffffff
16:41:55.675 [GPU legend.game.scripting.ScriptManager:139] ERROR:   25: 0xffffffff
16:41:55.676 [GPU legend.game.scripting.ScriptManager:139] ERROR:   26: 0x0
16:41:55.676 [GPU legend.game.scripting.ScriptManager:139] ERROR:   27: 0x0
16:41:55.676 [GPU legend.game.scripting.ScriptManager:139] ERROR:   28: 0x0
16:41:55.676 [GPU legend.game.scripting.ScriptManager:139] ERROR:   29: 0x6
16:41:55.676 [GPU legend.game.scripting.ScriptManager:139] ERROR:   30: 0x0
16:41:55.677 [GPU legend.game.scripting.ScriptManager:139] ERROR:   31: 0xb
16:41:55.677 [GPU legend.game.scripting.ScriptManager:139] ERROR:   32: 0x0
16:41:55.677 [GPU legend.game.scripting.ScriptManager:139] ERROR:   33: 0x0
16:41:55.678 [GPU legend.game.scripting.ScriptManager:142] ERROR: Call stack:
16:41:55.679 [GPU legend.game.scripting.ScriptManager:148] ERROR:   1: 0
16:41:55.682 [GPU legend.game.scripting.ScriptManager:148] ERROR:   2: 0
16:41:55.688 [GPU legend.game.scripting.ScriptManager:148] ERROR:   3: 0
16:41:55.688 [GPU legend.game.scripting.ScriptManager:148] ERROR:   4: 0
16:41:55.689 [GPU legend.game.scripting.ScriptManager:148] ERROR:   5: 0
16:41:55.689 [GPU legend.game.scripting.ScriptManager:148] ERROR:   6: 0
16:41:55.689 [GPU legend.game.scripting.ScriptManager:148] ERROR:   7: 0
16:41:55.689 [GPU legend.game.scripting.ScriptManager:148] ERROR:   8: 0
16:41:55.689 [GPU legend.game.scripting.ScriptManager:148] ERROR:   9: 0
16:41:55.690 [GPU legend.core.gpu.Gpu:465] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 14
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:797)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:723)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:512)
        at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:426)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:463)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
        at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:673)
        at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:731)
        at legend.game.combat.Bttl_800d.loadModelAnim(Bttl_800d.java:4852)
        at legend.game.combat.SEffe.FUN_80118984(SEffe.java:9900)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:894)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:530)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:458)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 10 more

**Comment by dragoonsouls** [comment]
make sense... since that scene is actually a DEFF package (one in which special visual effects are packed), so that scene must be heavily scripted.

**Comment by LordMonoxide** [comment]
Closing as we have NoDart issues listed elsewhere
