### ISSUE TITLE
Combat camera

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#31]
The combat camera is very glitchy. It jumps around a lot and the angles aren't quite right.

**Comment by Voreani** [comment]
The latest update to the run file seems to have fixed this.

**Comment by LordMonoxide** [comment]
Latest update greatly improves but does not fix this

**Comment by dragoonsouls** [comment]
Camera most of the time is correct.... but still get funky in some effects and Sharanda Shots

**Comment by dragoonsouls** [comment]
now it's better but most of the times, when camera close up (originally to Shana/Miranda) actually is doing this to Dart, also this happens for some Victory Animation stances... Precision of Camera improved!
