### ISSUE TITLE
Buying item in shop when inv is full just says "Cannot"

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#314]
![image](https://user-images.githubusercontent.com/437657/223425491-53a97747-9ee5-47b3-971b-a43cd50aafaa.png)

**Comment by Ink230** [comment]
Main branch behaviour, using keyboard
https://streamable.com/pejelf

Input PR behaviour, using controller
https://streamable.com/bhhhub

Notice how the text fully displays the first occurrence. Subsequent occurrences only display "Cannot".
