### ISSUE TITLE
Meta Discussion: Categorizing & Terminology of Retail Accuracy

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#324]
Issue #323 and some prior Discord discussions sparked the need for some definitions to be made. 

These can also be applied to future Issues as tags to guide proper solutions or to help educate others on where their solution lies.

---

### Retail Accurate
• 1:1 with retail behaviour, including crashes and bugs

• Ex: Lenus fight v2 crash, Martel sleepwalking, other graphical bugs (PS1-only)

### Retail Intent
• If it crashes / hangs in retail, it should be fixed
• If the behaviour is clearly bugged, it should be fixed

• Ex: Lenus fight v2, retail drops being n/99, graphical bugs / unused graphical effects, Addition input delay

### Retail Sensible
• If the behaviour is not bugged but is programmatically insensible, it should be changed
• If the behaviour is not bugged but provides a dramatic QoL improvement, it should be changed

• Ex: Loading times, Save Anywhere, Cutscene skips, Item slots, extra options like Fast Text, Auto-Text...etc

### Non-Retail - Mods
• Any changes capable through the Mod API

• Ex: Change Addition timings, EXP curves / tables / formulas /, game balance...etc

*Debugging features not included*

---

### Motivation
Clear definitions for the SC community will become increasingly important as development heads into the meaty nitpicky behaviour of the game, having an options menu, and, mainly, supporting mods.

- Knowing if a mod maintains Retail Accurate or Retail Sensible or is Non-Retail is a helpful filter. 

- This same filtering is also helpful for any options that are Retail Sensible (or below) that are provided in an options menu. These can also be presets in the options menu.

- Knowing if a reported Issue is solvable by a Retail Accurate, Retail Intent, or Retail Sensible solution is also important in communicating info top-down and to community users. If an issue is not resolvable by the core SC experience, it should be noted as 'Non-Retail / Mods' or so.

If one were to ask, "Should items be sorted alphabetically, by icon & alphabetically, or be like retail? The discussion is hard to have without the four above definitions being common place. But with the definitions its clear to see where each behaviour would lie in being a default (as Sensible or as Accurate), an options menu, or a mod.

### Discussion

So far it seems SC does everything up to Retail Sensible and has some light ruling on Non-Retail / assigning certain things as 'for mods". 

The discussion aims to resolve

- Where do you draw the line between the four categories for specific features, fixes, or behaviours?
- Are there more categories needed?
- How should these four categories be handled in an Options menu, in Issue tracking, mods...etc?

Think of things like item slots. They are clearly sensible to be increased but at the same time they imbalance the intended game play. Should it be an Options menu feature, should it be debugger only, should it be mods-only, should it be default behaviour? Does it exist in its own standalone category of "Independent Changes"?

Also remember, SC is Monoxide's project and he ultimately decides what goes, with or without community input.

**Comment by LordMonoxide** [comment]
I think these categories make sense, and _any_ category should be configurable on new game and/or in an options menu, including what mods are enabled, and options for mods

**Comment by dragoonsouls** [comment]
i really like the way you categorise the features, also the approaches and solvings are a thing here, since obviously there are different ways to achieve a similiar result. But it's good for anyone know how much game changes in each approach.

**Comment by Ink230** [comment]
• Discussion was open for two weeks
• Continued discussions can occur in Discord / new Issues
• Added to the Wiki
