### ISSUE TITLE
PS4 controller works when plugged in but not on bluetooth

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#336]
Got a report of this from a player. I don't have one so I can't test it myself. They tested with and without it plugged in. Wired was fine, bluetooth didn't register any input. No DS4windows or anything like that.

**Comment by theflyingzamboni** [comment]
This issue is inconsistent, as I (and I think at least one other person?) have used a bluetooth-connected DS4 controller without issue.

**Comment by LordMonoxide** [comment]
Closing for now, will reopen if anyone else has this issue
