### ISSUE TITLE
Low HP pose not happening sometimes

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#346]
See stream at around 21 minutes in the stream https://www.youtube.com/watch?v=Zu-kxBnF30c

Albert has red HP but is still standing in his normal pose. Shortly after, Albert is hurt again and switches to the pose.

**Comment by DrDeerface** [comment]
Not sure if this info will be useful in fixing the bug but: I have seen this happen in the Japanese retail version while playing on real hardware.

**Comment by LordMonoxide** [comment]
Haven't seen it happen in a while, will reopen if necessary
