### ISSUE TITLE
Magma Fish cause crash when attacking.

### ISSUE THREAD

**Issue by pyrestriker** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#360]
In Vol. Villude, the Magma Fish will cause the client to crash. At first I thought it was just Shana, but then after swapping her out for Lavitz, it happened again when the Magma Fish attacked Dart instead.
![image](https://user-images.githubusercontent.com/3858960/228113025-3b0b8d56-b6f4-4370-bfad-463eea2fd34d.png)
![image](https://user-images.githubusercontent.com/3858960/228113075-b9b25690-660b-409a-a441-f776db6865b5.png)

**Comment by Ink230** [comment]
## Video
https://streamable.com/cb4cny
