### ISSUE TITLE
Enemies bite attack wrong rendering - Main - Visual Bug

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#389]
As the Title mention, enemies which have bite/chewing attacks renders the effect in the Z axis and expand beyond the expected/retail limits.... some similar behaviour has been seen on Burn Out Magic.

**Comment by theflyingzamboni** [comment]
Fixed in PR 1735edc05caa3b81aa477a36131416ecc971b1e7
