### ISSUE TITLE
Wing Blaster Left-Top Glitch - Visual Bug

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#406]
While running the Wing Blaster DEFF it's noticeable a glitch at the left top of the screen, seems to be related to a Texture Overflow or could be another thing...
![wing_blaster_1](https://user-images.githubusercontent.com/17453375/230632521-bc2921f7-d125-497f-aa21-3dbf5586c2c6.jpg)
![wing_blaster_2](https://user-images.githubusercontent.com/17453375/230632535-ef51cdac-f837-4d20-81bb-38187fc96164.jpg)

**Comment by dragoonsouls** [comment]
To add more information... this same visual bug happens when casting Golden Dragon summon. Both cases Kongol and Belzac.

**Comment by theflyingzamboni** [comment]
Fixed by #459
