### ISSUE TITLE
Item mashing is broken

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#412]
SC seems not to be registering all inputs when mashing. This seems to become more of an issue when you mash faster. Swiping quickly, I cannot get the percentage above 110%, but mashing (which is slower) can get me over 150% (though this is still low).

**Comment by dragoonsouls** [comment]
i can confirm this... sometimes refuses to go beyond of 130%. The faster you do, the faster you get blocked to continue...

**Comment by greenbrettmichael** [comment]
its probably in this file
spell duration is ~2s. You get 2% per event. at 20 fps you need 1 event down on frame and 1 event up on frame. That means if your frame timing is perfect you would have ~20 total events possible (or 140%). If you have more frames, more would be possible
https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/blob/7581abe207469ea0f6b0e69e42630aa3a3fa8924/src/main/java/legend/game/input/InputMapping.java#L11
