### ISSUE TITLE
Dart started at D'lvl 5

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#43]
This may have been a fluke in my playthrough (possibly even something I did manually and forgot about) but Dart started at D'lvl 5. Someone needs to play through up until Dart gets his Dragoon spirit and see if it happens again.

**Comment by dragoonsouls** [comment]
It keeps D'lvl at 5, but now Dart don't appear with full sp lvl 5 anymore, also the SP gaining is more consistent

**Comment by Voreani** [comment]
As of my playthrough and obtaining Dart's dragoon transformation this issue is resolved.

**Comment by LordMonoxide** [comment]
Closing as this seems to be fixed now
