### ISSUE TITLE
App Port?

### ISSUE THREAD

**Issue by dracinn** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#442]
Without knowing any code would it be possible to use https://www.codenameone.com/ to convert to multiple platforms?

**Comment by LordMonoxide** [comment]
We already support Windows, Linux (+Steam Deck), and MacOS, and we're planning to support Android in the future. Unfortunately we make extensive use of native libraries which can't be ported using that service, so iOS isn't a possibility. Did you have any specific platforms in mind?

**Comment by dracinn** [comment]
Personally I was wanting to test it on Android and UWP for Windows and Xbox dev mode.

**Comment by LordMonoxide** [comment]
I looked into this, and unfortunately it can't be used for SC
