### ISSUE TITLE
Debugger no longer remembers UI color settings

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#464]
Custom color settings used to carry over between runs. Now it resets to the default value every time SC is run.

**Comment by theflyingzamboni** [comment]
Config file apparently only written to when app is closed, so pressing stop in the IDE to exit skips this code. Should config.conf be written to whenever a debug option is set?

**Comment by LordMonoxide** [comment]
We'd end up with a config save in a million different methods, since the config.conf file is going away and if you press the stop button you end up with memory leaks, I would recommend just closing the game normally whenever possible
