### ISSUE TITLE
GPU scaling performance issues with the inner moon

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#468]
CPU: 3900x
- All battle stages fail to hit target FPS on 2x scaler whilst in battle
- Most things like additions, items/spells that work on 2x elsewhere, struggle hard in the moon
- Each map of the inner core is giving the renderer a struggle

**Comment by LordMonoxide** [comment]
Closing because opengl
