### ISSUE TITLE
GPU scaling general rendering performance up to Hellena

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#469]
CPU: 3900x

### General Rendering Performance Pre-Hellena, 4x Scaling
Anything listed in the table is what I had to lower down to from 4x, to meet the FPS target.

|Scaling that met FPS Target|Issues|
|-|-|
|1x|`Feyrbrand Intro Cutscene`|
|2x|  `Battle Items` `Battle Spells` `Additions with Fixed z-coord side-view Camera` `World Map Menus` |
|3x|`Battle Model Idle Animations`  `Battle Additions` `Post-Black Screen Battle Encounter Effect` `Specific Camera Angles in any Fight` `Man in Hood Fruegel Cutscene 1` `World Map`|
|4x|`Everything Else`|

After leaving Seles, this is enough in of itself to figure out before proceeding with valid deeper tests.

I imagine CPUs half as good as the 3900x (aka most CPUs out there today for normies) will find most of the 3x issues only to be resolvable by going past 3x to 2x.

**Comment by theflyingzamboni** [comment]
Even at 2x I can't hit 30fps in the main menu on a 3700x.

**Comment by LordMonoxide** [comment]
Closing because opengl
