### ISSUE TITLE
Tasman encounter loading image is not scaled properly

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#470]
![image](https://user-images.githubusercontent.com/29797557/236639328-d202dc92-1088-45c7-ac82-7e35ce075ffe.png)

**Comment by theflyingzamboni** [comment]
Camera should rotate around the battlefield top-down before flashing to Dart and Tasman.

**Comment by LordMonoxide** [comment]
This is no longer happening
