### ISSUE TITLE
GPU scaling of small assets

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#474]
4x scaling
![image](https://user-images.githubusercontent.com/29797557/236644164-ea53058e-2541-41cc-96e4-91de1e3ee5c3.png)

2x scaling
![image](https://user-images.githubusercontent.com/29797557/236644176-c984efe1-854e-4e9a-bcb7-921dca1b1d7d.png)

1x scaling
![image](https://user-images.githubusercontent.com/29797557/236644173-7e83c64d-1901-4f86-8214-d9c5debacfe3.png)

More graceful rendering approach for these smallish assets to produce a more consistent look across a) all scales, b) actually render the thing in some way even on 1x.

**Comment by LordMonoxide** [comment]
Closing this as it's too much work and will be resolved with opengl
