### ISSUE TITLE
GPU scaling submap / battle object shadow scaling

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#476]
![image](https://user-images.githubusercontent.com/29797557/236644750-c6d24c29-00af-4ec4-b99c-deb150577762.png)
Can "shadows" in the smap be scaled/dithered/blended/better to a corresponding level of detail to the scale setting? They stick out real bad against the higher scaled models.

Looks like combat "shadows" do get scaled properly/better/somehow for certain camera angles.
![image](https://user-images.githubusercontent.com/29797557/236644436-7f41c21c-a70f-4dee-a0f0-e5852b071bd5.png)
![image](https://user-images.githubusercontent.com/29797557/236644442-01d803a3-23d1-41b5-b32f-1bbe53e3c1de.png)

**Comment by LordMonoxide** [comment]
I don't think these minor quality issues are worth spending time on since this is only temporary until opengl
