### ISSUE TITLE
ISO reader improvements

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#480]
Instead of looking for 1.iso, etc., just scan the directory and look for files with the correct data
- This will implicitly allow .bin files
- No need to give the files specific names, just copy them in

Look for ISOs from other regions and report that to the user as a friendly error message

**Comment by theflyingzamboni** [comment]
I would target what data to examine for the check (vs. something like hashing the file). I think it should be permissible to unpack a modded ROM.
