### ISSUE TITLE
No sound effects for Dragoon Doel single target attack

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#486]
Not getting any sound effects for Dragoon Doel's single target attack, all other sounds in the fight seemed to be alright

**Comment by LordMonoxide** [comment]
Did you notice any odd logs in the console when it happened?

**Comment by Chocolate06** [comment]
[Dragoon Doel Single Target.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/11447181/Dragoon.Doel.Single.Target.txt)

**Comment by Chocolate06** [comment]
This is not an issue within main.new-sound

**Comment by LordMonoxide** [comment]
Pretty sure it was #606 that fixed it since both fights have different forms, and the audio package switcher was busted
