### ISSUE TITLE
Dart failed to un-transform at the end of the Greham fight

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#49]

**Comment by LordMonoxide** [comment]
I haven't seen this happen yet. It may have been inadvertently fixed or it may have been a knock-on effect of another bug. Needs further investigation/playtesting.

**Comment by Voreani** [comment]
I will check it on my run once I reach this point and update on status of it.

**Comment by LordMonoxide** [comment]
Seems to have been fixed when fixing other dragoon bugs
