### ISSUE TITLE
Hellena Prison Second Tower Door placement, wrong

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#497]
Pretty much as title say, Hellena Prison second Tower door (where Shana is captive) seems to be in the wrong place...
![Door_Problem](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/17453375/688a4743-fb79-420c-bca5-0ed8af945b5c)

**Comment by Chocolate06** [comment]
Looks fine through the May 9th devbuild

![](https://cdn.discordapp.com/attachments/318595603636551701/1106931110241390694/image.png)
