### ISSUE TITLE
If a dragoon levels up, it says Dart unlocks a new addition

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#50]
Even if it wasn't Dart's dragoon that levelled up

**Comment by LordMonoxide** [comment]
I just had this happen, Rose's dragoon levelled up and it said Dart unlocked Hard Blade even though he didn't level up. Does this happen when a character's dragoon levels or was that a coincidence?

**Comment by Voreani** [comment]
This just happened with me. Rose's dragoon level increased to 2 and it informed me that Dart gained the addition More&More. I didn't actually have it available and could not select it upon going to its addition line in Dart's menu.
