### ISSUE TITLE
World Map: Flat Gray BG @ Max Zoom-Out

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#509]
Zooming out to the highest level on the world map results in a grey BG rather than the pre-rendered Endiness Map. I am on the latest devbuild from today, May 15.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/ea14be06-27fb-4c71-a8c2-bd9c42ae25db)

**Comment by DrewUniverse** [comment]
This also affects the Coolon Warp screen, and if it matters that BG is a bit darker.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/b49f35fb-c541-4756-a12e-e25f755bf35b)

**Comment by Chocolate06** [comment]
This appears to be from something merged on 5/13. My 5/12 build is fine but 5/13 build is not

**Comment by theflyingzamboni** [comment]
@LordMonoxide This bug was introduced by #503
