### ISSUE TITLE
Boss Battle Cutscene Crash

### ISSUE THREAD

**Issue by greenbrettmichael** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#534]
Crash after "Complete Virage" battle. Rose replaced Dart in party. Rose completed the "killing blow" and 3D cutscene started. Game crashed before Shana's "inner power" is released. "unlock_party" set to true in configuration.

"Full (as much as I can post on pastebin)" log:
https://pastebin.com/d3W6FQ6r

Error part of log:
18:08:01.189 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 15 crashed!
18:08:01.189 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 5562/1[3157]
18:08:01.189 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
18:08:01.189 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x142
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[15].storage[9] 17
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[0xc6b] 0x1
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xf
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x90000
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0x0
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0x11
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0xe
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0x10
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0x19
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0x1a
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0x1b
18:08:01.190 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0x1c
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0x19
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0x1a
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0x1b
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0x1c
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x18
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0x1a
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0x1b
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0x18
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0x6
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 170
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
18:08:01.191 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   9: 0
18:08:01.192 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 15
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:595)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:521)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:635)
        at legend.core.opengl.Window.run(Window.java:262)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:216)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
        at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:671)
        at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:729)
        at legend.game.combat.Bttl_800c.FUN_800ca100(Bttl_800c.java:2026)
        at legend.game.combat.Bttl_800c.FUN_800cb84c(Bttl_800c.java:2692)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:894)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:530)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:458)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 12 more
18:08:01.201 [Hardware legend.core.opengl.Window:92] INFO : Shutting down...

**Comment by LordMonoxide** [comment]
Hi @greenbrettmichael, this is a known issue with NoDart. It's a beta feature, which is why we don't have an in-game toggle for it yet. Long story short, the game expects specific characters to be loaded in some fights and cutscenes, and will crash if they aren't there.

We're in the process of compiling a list of these crashes. Until then, I would recommend having Dart in slot 1 for any fight that ends in a cutscene. The only in-combat crash I'm aware of is if you try to fight Kongol with a single character.

If you have any other questions, feel free to message us in the Legend of Dragoon Discord #modding channel (https://discord.gg/legend-of-dragoon)
