### ISSUE TITLE
Update Encounter Rate For "None" mode on World Map

### ISSUE THREAD

**Issue by greenbrettmichael** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#537]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/10648075/a65cc238-6add-4257-9478-ecacd7b44e2a)
Map encounter rate should be 0

**Comment by LordMonoxide** [comment]
Average is also broken, needs to be reduced
