### ISSUE TITLE
Textbox arrows are sometimes offset

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#59]
Can see many instances of this in the first cutscene

**Comment by Kona-lod** [comment]
This also happens with the "Blue-Yellow-Red" arrow. Screen cap to follow 
[Bug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9894658/Bug.zip)

**Comment by Kona-lod** [comment]
![image](https://user-images.githubusercontent.com/114179389/198853757-b0d98575-b362-4b08-95eb-70e3eb36e10d.png)
