### ISSUE TITLE
Dark Dragon crash on Light Special

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#593]
I was fighting the Divine Dragon Spirit, used ???'s special to turn everyone dragoon and then a bunch of turns later tried to use Rose's Dark Dragon. Have been unable to recreate, even on the same battle. Was playing on the devbuild updated the 29th when the crash occurred, tried to recreate on that and the music branch.

[Dark Dragon on Light Special.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/11630087/Dark.Dragon.on.Light.Special.txt)

**Comment by theflyingzamboni** [comment]
I cannot replicate this either.
