### ISSUE TITLE
Archangel crash on main.new-sound

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#599]
Archangel is crashing when attempting to do one of its moves. I've seen it successfully do the three headed elephant attack and it also heal me.

[Archangel.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/11639241/Archangel.txt)

**Comment by LordMonoxide** [comment]
This is a retail bug, the game does try to reference sounds that aren't loaded in the regular sword attack. Adding a workaround to avoid this.
