### ISSUE TITLE
Enemies can't seem to inflict status effects on players

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#60]
Poison, stun, etc., don't even get applied when enemies use attacks that supposedly have 100% chance of inflicting the status effect

**Comment by Voreani** [comment]
Received status affect of confusion on Lavitz during the Fruegel fight. First status affect affliction this entire game. Maybe status affliction is just extremely low probability?
