### ISSUE TITLE
UI MaxHP bug on campaign load screen

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#600]
![asd](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/115419005/5cd54700-161c-48a1-963b-948879ffd2a5)

MaxHP isnt updated for Physical Ring
UI is correct in game.

**Comment by Chocolate06** [comment]
Also the case for Dragon Helm

![max HP Dragon Helm](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/690e933c-55ef-47d2-8cd8-6c13736281f2)

**Comment by LordMonoxide** [comment]
FYI - this bug will still exist for old saves. Max HP will display properly once new saves are made.
