### ISSUE TITLE
Improve combat debugger

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#62]
-Allow fields to be 0 where valid
-Add SP and stat fields

**Comment by LordMonoxide** [comment]
I've added SP, speed, turn value, attack, defence, magic attack, magic defence, attack avoid, and magic avoid. There's a ton more we could add so I'm gonna leave this ticket open for discussion.

**Comment by theflyingzamboni** [comment]
Ability to edit dragoon spell lists

**Comment by dragoonsouls** [comment]
Maybe we should close this too? and move it to the wishlist?

**Comment by LordMonoxide** [comment]
Implemented
