### ISSUE TITLE
Dememulation Todo List

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#637]
# Mem Refs

## Bttl_800c
- ~~loadStageTim~~
- ~~callScriptFunction~~

## Bttl_800d
- ~~AdditionStarburstEffect10._0c (AdditionStarburstEffectRay10)~~
- ~~MonsterDeathEffect34.ptr_30 (MonsterDeathEffectDestructor30)~~
- renderAdditionNameChar
- ~~SpTextEffect40.ptr_3c~~

## Bttl_800e
- ~~EffectManagerData6c.effect_44~~
- ~~backupStageClut~~

## SEffe
- ~~GradientRayEffect24.ptr_00 (gradient ray instance)~~
- ~~StarChildrenMeteorEffect10.ptr_0c (presumably the array of Star Children star children)~~

# Ref Structs
- ~~AdditionOverlaysBorder0e~~
- ~~AdditionOverlaysEffect44~~
- ~~AdditionOverlaysHit20~~
- ~~AdditionStarbustEffect10~~
- ~~BattleStruct24~~
- ~~StarChildrenMeteorEffect10~~
- ~~StarChildrenImpactEffect20~~
- ~~WsDragoonTransformationFeathersEffect14~~
- ~~WsDragoonTransformationFeatherInstance70~~
- ~~MoonlightStarsEffect18~~
- ~~MoonlightStarsEffectInstance3c~~
- ~~GradientRaysEffect24~~
- ~~LensFlareEffect50~~
- ~~LensFlareEffectInstance3c~~
- ~~FullScreenOverlayEffect0e~~
- ~~GradientRaysEffectInstance04~~
- ~~GuardEffect06~~
- ~~MonsterDeathEffect34~~
- ~~ProjectileHitEffect14~~
- ~~ProjectileHitEffect14Sub48~~
- ~~RadialGradientEffect14~~
- ~~RaindropEffect0c~~
- ~~RainEffect08~~
- ~~ScreenCaptureEffec1c~~
- ~~ScreenCaptureMetrics8~~
- ~~ScreenDistortionEffectData08~~
- ~~SpTextEffectTrail10~~
- ~~WeaponTrailSegment2c~~

# Globals
Yes

**Comment by LordMonoxide** [comment]
Seeing as how we've already yote the memulation layer, I think we can close this
