### ISSUE TITLE
Severed Chains opening screen can be flipped (?random?)

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#663]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/e3ded5c4-d0f5-4772-9b36-c2c4a9750c8e)

Happens infrequently, seems to alternate from correct to incorrect on each launch. Latest main as of this ticket.

**Comment by LordMonoxide** [comment]
This has been rewritten since then
