### ISSUE TITLE
Okay. I just figured out what this Severed Chains thing is

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#668]
And I just figured out that this doesn't emulate. Well, if I can upscale the graphics, make them smooth (including the 2D backgrounds), and add custom cheats, I would be interested in giving this Severed Chains application a whirl.

**Comment by LordMonoxide** [comment]
Do you have a discord account? I'd recommend dropping into the #modding channel to discuss what exactly you're looking for. I'm the project lead (Monoxide), you can ping me there

https://discord.com/channels/307164262063669248/318595603636551701
