### ISSUE TITLE
Effects and models flipped

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#671]

**Comment by Ink230** [comment]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/5785a0c7-a1d9-4e50-9272-d970a9b10745)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/48d19710-27dc-4076-b6f4-beee66225975)

Good stuff.
