### ISSUE TITLE
Some CTMD are missed in the Rendering

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#69]
While internally those CTMD are processed (i believe), for some reason are not visible at the moment of playing...

**Comment by LordMonoxide** [comment]
Gonna need a lot more info than this. What CTMDs? Do you know if it's specific primitives? What situation?

**Comment by dragoonsouls** [comment]
I detect that in Shana Transformation, while i expect to see the "gray model" of Shana only see the other effects,
Custom Primitive Types involved: 
LSC 4 VERTEX GOURAUD NON-TEXTURED (SOLID)
LSC 3 VERTEX GOURAUD NON-TEXTURED (SOLID) 
as side note, This Primitive Type seems to be processed (checked using Breakpoint and match with the Binary File data)
Java File = Bttl_800e.java:
Code lines:
from 778 to 1028.
as additional info i will send two pics to compare Expected vs Obtained
![Shana_Gray_Missing](https://user-images.githubusercontent.com/17453375/189773749-0b80b409-36c1-484b-8cbc-a1e746993939.png)
![Shan_Gray_yes](https://user-images.githubusercontent.com/17453375/189773754-65c63dc4-decb-45b7-bc18-8cc9da9efe79.png)

**Comment by dragoonsouls** [comment]
also we have missing the Descending ray light

**Comment by LordMonoxide** [comment]
I have a strong suspicion that this is due to the DEFF animations being completely broken, rather than an issue with CTMD rendering

**Comment by LordMonoxide** [comment]
Most likely the same issue as #42
