### ISSUE TITLE
Dart Morphing issues

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#71]
While i got selected the Morphing options to "Normal" on the main game menu, in battle he transforms in Short time, this is happening to me at least using D'LVL 5, need to test into lower levels to see what happens...

**Comment by dragoonsouls** [comment]
> While i got selected the Morphing options to "Normal" on the main game menu, in battle he transforms in Short time, this is happening to me at least using D'LVL 5, need to test into lower levels to see what happens...

Lvl 1 Transformation is "Normal"

**Comment by dragoonsouls** [comment]
doing the leveling from 0 to 5 don't seems to show or cast the issue... but i'm trying early in the game... in the place that i notice this is in Black Castle... now i'm trying to farm the 5th lvl and in the next battle transform with full SP

**Comment by LordMonoxide** [comment]
No longer an issue
