### ISSUE TITLE
Fruegal battle crashes

### ISSUE THREAD

**Issue by montagical** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#711]
Hello,

After defeating the left senior warden in Hellena Prison (the first time at the beginning of the game) the game crashes. I have repeated the fight twice now and as soon as the senior warden casts gushing magma upon death the game crashes. Not sure what's going on. Running the game at 2x resolution (on most recent build as of 9/17/23). Everything else has been smooth up until this fight. Any ideas? Thank you!

**Comment by LordMonoxide** [comment]
Are you using the devbuilds, or Recommended Build 2.1? And can you attach the end of the console log (including stack trace)?

The stack trace will look something like this:
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/437657/1a3a2f94-eed1-40e4-b24d-f2f008b5c44d)

**Comment by LordMonoxide** [comment]
Closing as no response
