### ISSUE TITLE
Hoax collision bug when Lavitz is following behind Dart

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#724]
He stucc
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/ea8e4210-4313-434e-8553-ab385ceed508)
Save file
[hoax.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/12706961/hoax.zip)

**Comment by LordMonoxide** [comment]
Also bugged after finishing the very first battle in Seles. You can't move off of the dead body unless you're running

**Comment by LordMonoxide** [comment]
Caused by 1a61a155cd295fa792cf58c6df807e2c6c37919a
