### ISSUE TITLE
Victory Animation is not working as intended

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#73]
As the title says Victory Animations, shown in battle end, are not working as intended, the only character who perform it is Dart, the rest are just standing in "Idle Pose". This has been check to Lavitz/Albert, Shana, Rose and Haschel.

**Comment by Voreani** [comment]
As of the new updated files this still holds true.

**Comment by dragoonsouls** [comment]
Something could be wrong in one of the Methods in charge of the 3 Combatants animations...
