### ISSUE TITLE
Fireflies absent in Lime Cave

### ISSUE THREAD

**Issue by Voreani** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#77]
The rock fireflies aren't actually visible in the lime cave. When you go to where they are in the cave you get the exclamation point to interact with them, but they aren't actually visible themselves.
![image](https://user-images.githubusercontent.com/113736695/190860633-fefb74c6-9473-4893-8379-6c9bf920e0d7.png)

**Comment by LordMonoxide** [comment]
Fixed
