### ISSUE TITLE
[OpenGL] Font character cut-off (letter g)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#782]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/142cd89b-512e-40f2-afc9-e8bed6cd33eb)

**Comment by LordMonoxide** [comment]
Also applies to parentheses

**Comment by LordMonoxide** [comment]
Fixed by #1041
