### ISSUE TITLE
[OpenGL] Indicator icons not rendering (encounters, entrances and exits, etc.)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#804]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/2f7b6481-81d9-4f1e-8ea3-f6d99bbe544a)

**Comment by LordMonoxide** [comment]
#925
