### ISSUE TITLE
[OpenGL] Save Point invisible for the most part. 

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#807]
It makes Dart glow when he steps into a Save point, but otherwise the save point does not appear. 
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/7d219dbe-49af-4703-948f-0159a849c779)

**Comment by LordMonoxide** [comment]
#926
