### ISSUE TITLE
Weird things happened to action bar after being attacked

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#842]
https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/feaefa67-89f8-4035-9416-8e93bc73476b

Not currently sure how to replicate.

**Comment by LordMonoxide** [comment]
Fixed in 341a7dd9ff8a7b98ea5bf40378d6345f30419de3
