### ISSUE TITLE
Crates and Treasure Chest not shown correctly

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#85]
Some Crates (with items) or Treasure Chest are not correctly displayed in-game, some of them even are invisible

**Comment by LordMonoxide** [comment]
This is probably the same thing causing character models to render with some missing parts (like Dart in the Shana hospital scene in Lohan)

**Comment by Voreani** [comment]
In Lohan the dodging game doesn't show the objects to avoid/dodge therefore making it unplayable.

**Comment by LordMonoxide** [comment]
Fixed
