### ISSUE TITLE
Smap texture issues

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#858]
Will create a comment for each smap I notice

**Comment by Chocolate06** [comment]
smap12

Also get lines of the teal color when the smap is moving up/down

![notsosecret](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/69a2eadf-70ba-4d79-8277-67b5e2749f81)

**Comment by Chocolate06** [comment]
smap10

![smap10 glview](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/b498eb9a-bd6b-4750-8b5d-2039ee94a48d)
![smap10vram](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/ebf2f364-06c8-4732-9c91-7dd908fed8ac)

**Comment by theflyingzamboni** [comment]
For the small gaps over the chroma key, I suspect there is an fp rounding issue at fault, as the gaps appear to be one pixel, and appear/disappear as the camera moves around.

**Comment by LordMonoxide** [comment]
Fixed a while ago
