### ISSUE TITLE
WMAP Between Lidiera and Undersea Cavern not Rendered correctly

### ISSUE THREAD

**Issue by FullMetalAggro** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#864]
Darts feet are gone and there are no dots like the rest of the World Map.
![Screenshot 2023-11-17 171415](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150860467/9e3ac758-84af-48e5-b9be-1227584aa480)

**Comment by theflyingzamboni** [comment]
May be mispositioned in retail as well, but can't tell due to lack of proper depth.
