### ISSUE TITLE
Boat object rendering incorrectly (Bale, Lidiera)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#878]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/0cb0766c-ab91-414a-97ab-0fe90b5e7e39)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/820cf506-9ccf-4d95-ac89-455d034cc346)

**Comment by DrewUniverse** [comment]
Intended appearance: 
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/cfed4d46-bf2f-4447-a1fb-6873f82ca94b)

**Comment by theflyingzamboni** [comment]
See #795 for another example.

**Comment by LordMonoxide** [comment]
This is no longer an issue
