### ISSUE TITLE
Collision issues

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#9]
Collision is probably about 90%, but not quite accurate. For example, rubbing against some collision barriers can cause you to teleport into the abyss.

**Comment by LordMonoxide** [comment]
This may have been fixed when I fixed the major model glitching, I haven't seen it happen in a while

**Comment by LordMonoxide** [comment]
Collision is almost perfect but occasionally you can get hitched on parts of the geometry that you can normally slide along (the twisty path in the Prairies after Hellena where Lavitz gets arrowed for example)

**Comment by dragoonsouls** [comment]
> Collision is almost perfect but occasionally you can get hitched on parts of the geometry that you can normally slide along (the twisty path in the Prairies after Hellena where Lavitz gets arrowed for example)

i remember get stuck in some places because of the Collision, so maybe it's a retail bug...

**Comment by theflyingzamboni** [comment]
@LordMonoxide Did you finish fixing collision in that one branch? I can't remember if that branch was merged to rc/main yet.
