### ISSUE TITLE
Potential return of texture corruption in 3D models.

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#937]
Observed via in-engine cutscenes.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/74f7ff89-8999-4a3f-aaf1-c1c16d369bc6)

**Comment by LordMonoxide** [comment]
This may have been caused by the changes to the asset loading code, rather than the previous texture corruption bug

**Comment by theflyingzamboni** [comment]
Shana, what happened?!

**Comment by DrewUniverse** [comment]
Another instance. Dart trying to be Rose for his first transformation. Complete with an evil goatee.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/d6cbabf1-fe2f-49ac-876a-0f5117c02e74)
