### ISSUE TITLE
Wrong initial camera position for Mayfil submap on first visit.

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#964]
When first arriving in Mayfil, the room after the teleporter should start at the top of the submap, showing a large tower, then panning downward to the walkable area. Instead, the camera starts at the bottom of the submap, only moving a few pixels before the party expands outward from Dart. SC on top, intended at the bottom of this post.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/a5f45a1f-2fc0-4526-93b6-7328db95de06)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/ded4eb0f-8bbd-4c2b-a8bb-c634462bbe40)

**Comment by LordMonoxide** [comment]
Fixed with #971
