### ISSUE TITLE
WMAP - Dart's walk anim seems bugged in the knees; run anim more bugged (skips around on loop?)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#965]

**Comment by LordMonoxide** [comment]
Can you post a video? I'm not seeing it

**Comment by DrewUniverse** [comment]
![walkbug](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/20f91901-e2ad-437c-b85e-ffbd0883d20c)
![runbug](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/78b763ff-d5be-4241-985e-a9dbf90c4715)

**Comment by LordMonoxide** [comment]
Assigning this to @dragoonsouls to check out when he has time

**Comment by dragoonsouls** [comment]
Seems to be SC bugged... at least in my conversion looks just fine... but keep in mind... i use the twelve decimals in the precision of the floating point for Vertex position... this surely helps a little in such a tiny model...

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/17453375/a8c0f828-10a6-40db-b78f-30a073ebdd63


https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/17453375/3bd0492b-6845-41f7-90a8-02b28ad665a5

Also keep in mind... the WMap mini models and SubMaps mini models are actually MINI... no joke... ratio around 1:10 or 1:15 compared to the size of the Battle Models...

**Comment by LordMonoxide** [comment]
I don't think I'm seeing an issue in the SC model, do you see anything wrong @dragoonsouls ?

**Comment by LordMonoxide** [comment]
Tested with frame advance, no issue
