### ISSUE TITLE
Crash on battle start, stage.dobj2s_00[i] is null

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#977]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/01beb0fd-3c78-4a09-805b-40c67093133b)

Was walking around on map 459.

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/3037c23c-8656-4dac-a38a-ccd86501fb65)

Was on map 24.

**Comment by LordMonoxide** [comment]
Can no longer reproduce
