### ISSUE TITLE
Laptos have wrong CLUT

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#991]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/9603ae2c-ac2c-48ca-988d-9e969c61ab84)

Retail:
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/1c44ddea-17dc-49e9-9361-d90c7f3b0601)

Corrected itself when I entered and exited menu.

**Comment by theflyingzamboni** [comment]
Teleporter effect is wrong as well. placing here because I think there's a chance this is the same issue.

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/1de211d2-e048-4eac-9a93-75b274caabb9)

**Comment by LordMonoxide** [comment]
This is probably related to the sobj texture changes

**Comment by theflyingzamboni** [comment]
That is my assumption.
