### ISSUE TITLE
Many elements appear to be off-center

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#996]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/e422e784-cb05-4e9c-8721-ca1ed0720b4a)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/cc047a5a-9cf4-4cf3-978e-5fa3ce48eb04)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/6cd7a5e7-9069-46c0-ab0f-f2d620e65cb4)

**Comment by dragoonsouls** [comment]
In Donau (after the Night Scene) get this as result, Collisions displaced to the left of the SubMap Textures
![Donau_offset](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/17453375/4e0a8482-4d7b-4cda-b0ee-f0a168014bf8)
